
jobs:
  job.one:
    job: SimpleJob
    description: My Job is simple 
    cron: '*/1 * * * * ?'
    config:
      color: blue
      an_array:
        - one
        - two

queues:
  /queue/response:
    durable: false
